### PR TITLE
PWX-22163: Compile fixes for 5.15.0-1.el7.

### PR DESCRIPTION
**Pull request by jrivera-px**
Signed-off-by: Jose Rivera <jose@portworx.com>

**What this PR does / why we need it**:
PX fuse fails to compile on 5.15.0-1.el7.   implicit declaration of function ‘alloc_disk’  & error: ‘GENHD_FL_UP’ undeclared .  Use '__alloc_disk_node(...)'  & 'disk_live()' instead.
**Which issue(s) this PR fixes** (optional)
Closes #: PWX-22163

**Special notes for your reviewer**:

### CODE REVIEW

**Review by sulakshm — APPROVED** [review]
looks good
